### ISSUE TITLE
Attribute landing page with trailing slash

### ISSUE THREAD

**Issue by Alex-MaxServ** [EmicoEcommerce/Magento2AttributeLanding#11]
The policy of url's in our current project is like;

- All pages ends with /
- Except product pages, they need to end with .html

Categories and contentpages work fine with trailing slash. Attribute landingpages doesn't allow trailing slash. While trying to save the URL path including trailing slash, only without trailing slash is saved.

Is it possible to allow trailing slashes on attribute landingpages?

**Comment by edwinljacobs** [comment]
Hello,

We will add this to our backlog. This would become an extra setting as we dont want to use the category url suffix (that would change the urls of existing installations). In the meantime you could write an after plugin on method

https://github.com/EmicoEcommerce/Magento2AttributeLanding/blob/2c2b1fc43c31ea55a900a42f3c55ea17b3f72f57/src/Model/LandingPage.php#L405

To append the slash yourself.

This code is called at
https://github.com/EmicoEcommerce/Magento2AttributeLanding/blob/2c2b1fc43c31ea55a900a42f3c55ea17b3f72f57/src/Observer/UrlRewriteGenerateObserver.php#L54

With kind regards

**Comment by maxserv-woostelbos** [comment]
Hi, 

We changed the getUrlRewriteRequestPath method and our url_rewrite is correct now. 

But when we look at this template (layered navigation) the method called renderAnchorHtmlTagAttributes() is used for the href. 

`vendor/emico/tweakwise/src/view/frontend1/templates/product/layered/default.phtml`

This method still looks at the landingpage url-path and not the url-rewrite. So when we hover over a filter the url without trailing slash is shown and after that redirected to the one with trailing slash. 

How can we make sure the url-key is used in the href for the layered nav items?

**Comment by edwinljacobs** [comment]
There have been several releases for this issue.

https://github.com/EmicoEcommerce/Magento2Tweakwise/releases/tag/v2.3.0
https://github.com/EmicoEcommerce/Magento2AttributeLandingTweakwise/releases/tag/v1.1.0
https://github.com/EmicoEcommerce/Magento2AttributeLanding/releases/tag/v1.1.0

There is an added option to append the category url suffix to the landingspage urls (Stores > Configuration > Emico > attributelanding) If set to yes it takes the category url suffix and appends it to the landingpage url (in the rewrite table)

I have not checked view/frontend/templates/product/layered/default.phtml
