### ISSUE TITLE
Landing page with multiple filter attributes on one attribute only hide the first filter

### ISSUE THREAD

**Issue by GautierI** [EmicoEcommerce/Magento2AttributeLanding#12]
Normally the active filters are hidden (its an option), but if we add multiple values for the same filter, like color, only the first value is hidden and the rest is still visible in the landing page.
These other filters should also be hidden.

**Comment by edwinljacobs** [comment]
Hi sorry for the late reply, we will look into it.

**Comment by edwinljacobs** [comment]
Again a late reaction however this issue should be fixed in 

https://github.com/EmicoEcommerce/Magento2AttributeLandingTweakwise/releases/tag/v1.1.1

With kind regards
