### ISSUE TITLE
Can't create any overview or landing page

### ISSUE THREAD

**Issue by vasiok32k** [EmicoEcommerce/Magento2AttributeLanding#17]
Hello
After installing the module but was found issues during creating landing page and overview page, after click on button Save or Save and Continue Edit, page will be frozen and got error in the console related of Page Builder
![image](https://user-images.githubusercontent.com/10946737/98943229-d8567980-24f7-11eb-94ad-a9ef2906ee7f.png)
I partly investigated issue and it seems like  it's caused by wrong component structure, a component within a component that can't handle a component. As a solution could be that move Page Builder instances behind the button that will need to click a button to open the Page Builder - need to add that config line in appropriate places where adding Page Builder instances:

`<item name="pagebuilder_button" xsi:type="boolean">true</item>`

It will solve the problem but will lead to another PHP error like this:
![image](https://user-images.githubusercontent.com/10946737/98942902-64b46c80-24f7-11eb-8bef-ec2c3f4d5775.png)
Could you please fix that issues or at least tell me please how to could be resolved?

**Comment by edwinljacobs** [comment]
Hi,

I assume you are on enterprise? Which version exactly? To be honest i'm not sure why this is an issue. I would have to investigate that, sadly I cannot do that today. I think I will be able to provide you with an update on Wednesday. By the way, I assume you are using this in combination with tweakwise?

I did take a quick look to find similar issues, maybe this helps in the meantime? https://github.com/mirasvit/module-blog/issues/162

With kind regards

**Comment by vasiok32k** [comment]
Version is 2.3.5-p2

**Comment by vasiok32k** [comment]
I will really appreciate you if you will help me to fix it (that for that link but I already looked that resource before and it not helped me unfortunately)

**Comment by edwinljacobs** [comment]
Hi,

I took a quick look, It seems that we have been sloppy with our method definition in 
Emico\AttributeLanding\Model\IrlRewriteService::generateRewrite();

```diff
diff --git a/src/Model/UrlRewriteService.php b/src/Model/UrlRewriteService.php
index 0d0650f..b22c72c 100644
--- a/src/Model/UrlRewriteService.php
+++ b/src/Model/UrlRewriteService.php
@@ -109,10 +109,10 @@ class UrlRewriteService
     }
 
     /**
-     * @param LandingPage $page
+     * @param UrlRewriteGeneratorInterface $page
      * @param string|null $suffix
      */
-    public function generateRewrite(LandingPage $page, string $suffix = null)
+    public function generateRewrite(UrlRewriteGeneratorInterface $page, string $suffix = null)
     {
         $urlRewritesToPersist = [];

```

You could try to apply this patch and check if that works (I haven't tested it). The overview page functionality is seldom used and perhaps under developed.... Ill look into this with more detail wednesday.

With kind regards

**Comment by edwinljacobs** [comment]
I made a note for testcases as this kind of stuff should not happen

**Comment by vasiok32k** [comment]
Thanks seems like it helps for overview page, but landing page still can't be save, getting that error
![image](https://user-images.githubusercontent.com/10946737/99079510-bc6ed880-25c8-11eb-8f3d-9eef1d0272db.png)

**Comment by vasiok32k** [comment]
Will wait Wednesday

**Comment by edwinljacobs** [comment]
Hi,

I created release https://github.com/EmicoEcommerce/Magento2AttributeLanding/releases/tag/v1.1.3 for this issue.
It should be fixed now. One thing though, I assume you are using this module in combination with
https://github.com/EmicoEcommerce/Magento2Tweakwise
https://github.com/EmicoEcommerce/Magento2TweakwiseExport
https://github.com/EmicoEcommerce/Magento2AttributeLandingTweakwise

The reason I'm asking is that if this is not the case then it wont work. The mechanism that should apply the filters in the field Filter attributes (in the form above) to the product list is not implemented in native magento. See https://github.com/EmicoEcommerce/Magento2AttributeLanding/blob/055f632b8e442e1ba64547d36a4089a60841dab2/src/Model/FilterApplier/MagentoFilterApplier.php#L24

**Comment by vasiok32k** [comment]
Hi
Thanks a lot for you time, seems like it fixed and works well.
I also created PR about error related of Page Builder, please review it and merge if it acceptable for you (because moving Page Builder instances behind the buttons really fixing that problem)
https://github.com/EmicoEcommerce/Magento2AttributeLanding/pull/18

**Comment by edwinljacobs** [comment]
Thanks for taking the time to make a PR! it has been released in https://github.com/EmicoEcommerce/Magento2AttributeLanding/releases/tag/v1.1.4

I hope this solves your issues, good luck!

**Comment by vasiok32k** [comment]
Yes, it solved my issues, thanks for your activities and help.

**Comment by vasiok32k** [comment]
Tell me please how to became a contributor to be in this list?
![image](https://user-images.githubusercontent.com/10946737/102625204-ce0a4980-414d-11eb-91d9-5b0903439c13.png)

**Comment by edwinljacobs** [comment]
Yeah weird, that doesn't work, perhaps https://stackoverflow.com/questions/40644933/not-showing-as-a-contributor-on-github helps, the accepted answer is not applicable but maybe something in your email settings (the second answer)?

**Comment by vasiok32k** [comment]
Hi
I contacted with support of the Github and we resolved the problem, thanks.
