### ISSUE TITLE
Final breadcrumb element of a landing page should not be a link

### ISSUE THREAD

**Issue by aadmathijssen** [EmicoEcommerce/Magento2AttributeLanding#23]
The final breadcrumb element of an attribute landing page contains a link. However, because this link should point to the page itself, it is useless. So it can better be removed. This is also consistent with category breadcrumbs where the final element is also just text.

This can be fixed by removing the `link` property from the `landingpage` crumb in `Emico\AttributeLanding\Block\Catalog\Breadcrumbs::addLandingPageBreadCrumbs`.

This change will also resolve the issue that the landing page link is a relative URL, which results in linking to a non-existing page.

**Comment by bramstroker** [comment]
Fixed with #28
