### ISSUE TITLE
Incorrect category filter href when on attribute landing page

### ISSUE THREAD

**Issue by pimbrab** [EmicoEcommerce/Magento2AttributeLanding#32]
When an attribute landing page is active, the category links do not include any query parameters and just point to the category.
I would expect the category link to include a query parameter based on the current attribute landing page settings.
The quantity next to the category title is accurate though, but the url is not. This does work when not on an attribute landing page.

**Comment by ah-net** [comment]
Late reply, but I can't seem to reproduce this issue in the latest version. Do you still have this issue?
