### ISSUE TITLE
Trailing slash for Attribute Landing pages

### ISSUE THREAD

**Issue by koentjeh** [EmicoEcommerce/Magento2AttributeLanding#49]
Some stores of our customers use a trailing slash for Attribute landing Pages. The stores use the fallback url (Canonical URL empty) to generate a canonical url. The trailing slash fix implemented in the pull-request below causes the trailing slash to be removed:
https://github.com/EmicoEcommerce/Magento2AttributeLanding/pull/45

It would be useful to implement a setting to allow a trailing slash since now unexpected behaviour occurred after updating. Now it should have been a minor update 3.1.0 instead of a patch/bugfix 3.0.4

Leaving this issue untouched wil cause unexpected behaviour after updating to 3.0.4 or later.

**Comment by ah-net** [comment]
@koentjeh Sorry for the late reply.

Is it still an issue with the latest version? Because i can make an ALP page with an trailing slash. And the trailing slash isn't removed in the canonical url.
