### ISSUE TITLE
Admin grid shows only data of last record

### ISSUE THREAD

**Issue by mischabraam** [EmicoEcommerce/Magento2AttributeLanding#58]
When I open the grid of attribute landing pages, only data is shown from the last record. When I use a filter on ID (for example), the correct data is shown. However, when I remove the filter, again only the data from the last record is shown.

Module is version 4.0.0 on PHP8.1 with Magento Commerce 2.4.5-p1.

<img width="1788" alt="Screenshot_2022-11-21_at_14_04_00" src="https://user-images.githubusercontent.com/19824986/203062833-84677272-1472-47f2-97f2-be6cd842d521.png">

I moved from `tweakwise/magento2-attributelanding` to `emico/m2-attributelanding` like suggested in https://github.com/Tweakwise/Magento2AttributeLanding/issues/5 which doesn't seem to resolve the issue.

**Comment by mischabraam** [comment]
I've created two video's see link below (available for one month).
https://files.fm/u/6q4ddj2s8

**Comment by ah-net** [comment]
@mischabraam Thx. I'll take another look at this. And see if i can reproduce this again on the latest version.
