### ISSUE TITLE
Missing Header Image logic

### ISSUE THREAD

**Issue by leonhelmus** [EmicoEcommerce/Magento2AttributeLanding#91]
Hello Tweakwise,

For a client of ours we would like to have a header image. I see in the db_schema.xml there was effort put into to make sure this was possible with the column 'header_image', but no other logic has been created for it. 

Is this still something that will be added later?

**Comment by ah-net** [comment]
@leonhelmus There are currently no plans to implement this. I think it may be leftover from old code.
